spring:
  datasource:
    username: lianmeda
    password: Med@01703
    url: jdbc:mysql://119.23.170.45:3306/obis_srsrmyy_dev?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

server:
  port: 9090

config:
  jwt:
    secret: qsS0stzLhORJFkouQkpFTA3pF5JBnmCmctK7YmNNoeXf6plHdBIG/xJ3+s9JFY6sB0vwUsJhoL3oFGmQq0l4Yw==
    expire: 604800000


